-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE SEQUENCE IF NOT EXISTS private.employees_id_seq;
-- ALTER TABLE private.employees ALTER COLUMN id SET DEFAULT nextval('private.employees_id_seq');
-- SELECT setval('private.employees_id_seq', (SELECT MAX(id) FROM private.employees));
